# -*- coding: utf-8 -*-
"""prophet_forecast_daily.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Br_oSNJIzonQOi3LWdgOq8PQadttKvnb
"""

import pandas as pd
from prophet import Prophet

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/daily_hire-term_prophet.csv')

m = Prophet()
m.fit(df)

future = m.make_future_dataframe(periods=365)
future.tail()

forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

fig1 = m.plot(forecast)

fig2 = m.plot_components(forecast)

from prophet.plot import plot_plotly, plot_components_plotly

plot_plotly(m, forecast)

plot_components_plotly(m, forecast)

# Create a dataframe of the results
df_results = pd.DataFrame(m.predict())

# df_results.head()

df_results.to_csv('/content/drive/MyDrive/All The Things/Career/NBCU/prophet_df_output_daily.csv', index=False)
